print("Digite seu nome:")
nome = input()

print("Seu nome em letras maiúsculas:")
print(nome.upper())
print("Seu nome em letras minúsculas:")
print(nome.lower())
print("Quantidade de letras no seu nome:")
print(len(nome) - nome.count(" "))
print("trocando seu último nome por `do Inatel` :")
print(nome.rsplit(" ", 1)[0] + " do Inatel")
